### PR TITLE
Add netloaded commandline to args.

### PR DESCRIPTION
**Pull request by machinamentum**
Current functionality removes the feature to set command line args from 3dslink. This creates a compromise by adding the command line arg sent by 3dslink to the arg list, while still having arg0 be the executable path.

### CODE REVIEW

**Comment by fincs** [comment]
I don't know why was this changed. I'll talk to smea about changing it back to how it was.

**Comment by suloku** [comment]
I've been trying to pass selected title ID from the title browser when launching a homebrew as argv[1] but I can't manage to acomplish it, not even copying this code, which works fine for netloaded 3dsx files.

The goal for that is to allow svdt to know the title it is running on, to automatically get the title name and more importantly, enable secure value patching.

Any tips?

**Comment by machinamentum** [comment]
What is actually your problem? What output does printf("%s\n", argv[1]) give you? Are you sure you're getting the title name correctly? We can't begin to understand what problem you're actually facing without understanding the data associated with that problem.

**Comment by suloku** [comment]
Sorry, I'l explain my problem with a simple example: I can't figure out why changing your code like this won't pass "Hello World" as argv[1] to all booted 3dsx

[code]
		if (1)
		{
			snprintf((char*)&argbuffer[0]+argbuffer_length, 0x200*4 - 4 - argbuffer_length, "%s", "Hello World");
			argbuffer_length += strlen((char*)&argbuffer[0]+argbuffer_length) + 1;
			argbuffer[0]++;
		}
[/code]

**Comment by machinamentum** [comment]
You have 0x2004: in the original code, it was 0x200 * 4 which evaluates to 0x800, the length of the buffer. For args to work, they need to be carefully packed into the buffer with only a null character separating them iirc.

**Comment by suloku** [comment]
I don't know why it appears as 0x2004, I copy pasted from your github commit, it is OK in my code, so that's not the reason. Sorry I didn't notice the typo.
In fact, if I click the edit button on my previous comment, 0x200*4 is written indeed.
snprintf is supposed to append a null character at the end, so that shouldn't be a problem.

**Comment by mtheall** [comment]
```
    if (1)
    {
        size_t limit = 0x200*4 - 4 - argbuffer_length;
        char   *buf  = (char*)&argbuffer[0] + argbuffer_length;
        int    len   = snprintf(buf, limit, "%s", "Hello World");

        if((size_t)len < limit)
        {
            argbuffer_length += len + 1;
            ++argbuffer[0];
        }
        else
        {
            /* uh-oh trouble; not enough space to fit the args */
        }
    }
```

Sure this is more verbose and easier to read, but it is certainly faster than doing a `strlen()` after you already know what the length is going to be (returned from `snprintf()`).

**Comment by suloku** [comment]
Ok, after some tests the problem seems to happen only when booting a 3dsx file with the title selector, but argv[0] is properly set. Changing argv[0] (i.e. put Hello world instead of executable path) makes it unable to boot at all.

**Comment by WinterMute** [comment]
This was fixed in git master.

**Pull request closed without merging**
