### PR TITLE
Dark theme (alpha)

### PR DESCRIPTION
**Pull request by s3r1alpari4h**
Added dark theme, not sure how it will turn out yet, will add code to activate in main.c later

### CODE REVIEW

**Comment by phase** [comment]
Is there a way to change the theme without manually changing the code?

**Comment by s3r1alpari4h** [comment]
Not yet. That'd be an idea though.

**Comment by s3r1alpari4h** [comment]
Maybe loading from a configuration file on the sdcard

**Comment by HandsomeMatt** [comment]
Loading the colours themselves from a configuration file is a better idea.

**Comment by s3r1alpari4h** [comment]
We literally just said that at the same second xD

**Comment by HandsomeMatt** [comment]
I thought you meant storing the theme option in config. I thought I'd clarify that it should be the colours stored in the configuration and not hardcored in the source code.

**Comment by suloku** [comment]
Already done here:https://github.com/suloku/3ds_hb_menu/tree/patch-1?files=1

Configurable themes among many other things.

**Comment by s3r1alpari4h** [comment]
Will never get merged, closed

**Pull request closed without merging**
