### PR TITLE
Localized regionfree launcher smdh to all languages

### PR DESCRIPTION
**Pull request by handsomematt**
Translations below, did my best from my education to confirm latin based languages are roughly correct, the rest are google translate, but should be good enough.

Japanese: リージョンフリーのランチャー - 地域のゲームカードのうちを再生
English: Region free launcher - Select this to play an out-of-region gamecard
French: Région lanceur gratuitement - Jouer un hors de la région de la carte de jeu
German: Region kostenlos Launcher - Spielen Sie eine aus der Region von Spielkarten
Italian: Regione libera launcher - Gioca un fuori regione gioco di carte
Spanish: Región lanzador libre - Juega un fuera de la región de la tarjeta de juego
Simplified Chinese: 区域内免费启动 - 发挥出区域游戏卡
Korean: 지역 무료 실행 - 지역 게임 카드의 아웃 플레이
Dutch: Regio vrij launcher - Speel een van de regio game card
Portugese: Região lançador livre - Jogar um jogo de cartão região
Russian: Регион бесплатный запуска - Играть отказа от региона игровой карте
Traditional Chinese: 區域內免費啟動 - 發揮出區域遊戲卡

regionfreelocalisation

(works with #14) (if anyone has any corrections they want to make, comment below and I'll commit changes)

### CODE REVIEW

**Comment by fincs** [comment]
Spanish should have been "Lanzador de región libre - Jugar con una tarjeta de juego de cualquier región"
Japanese (AFAIK) should have been "リージョンフリーのランチャー - 外来のゲームカードと遊びます"

**Comment by HandsomeMatt** [comment]
cool thanks, got a few more from native speakers too:

Japanese: リージョンフリーのランチャー - 外来のゲームカードと遊びます
French: Région indépendant lanceur - Sélectionnez cette option pour sélectionner une carte à jouer qui ne soit pas dépendante région
German: Regions unabhängiger launcher - Wähle dies um eine Spielkarte zu wählen welche nicht Regionsabhängig ist
Spanish: Lanzador de región libre - Jugar con una tarjeta de juego de cualquier región
Italian: Launcher senza restrizioni regionali - Selezionare per giocare un gioco fuori regione

**Comment by Brawl345** [comment]
I would use this for german:
Regionsfreier Launcher - Wähle dies, um ein Spielmodul aus einer anderen Region zu spielen.

**Comment by profi200** [comment]
@Brawl345 The first part sounds... shit. I would keep it in english.

Region free launcher
Wähle dies, um ein Spielmodul aus einer anderen Region zu spielen.

**Comment by Brawl345** [comment]
@profi200 yes you are right, that sounds better ^^

**Comment by smealum** [comment]
thanks for your contribution.

can i ask where you got your native speakers ? the french version at least is completely off, which doesnt inspire lots of confidence in the rest

**Comment by HandsomeMatt** [comment]
the French one was just some random in #3dsdev said he was a native
speaker, the Italian and German translations are from friends, I'll commit
the other corrections people have posted when I wake up

**Comment by HandsomeMatt** [comment]
okay fully localized from native speakers and what was suggested in these comments

JP: "リージョンフリーのランチャー" - "外来のゲームカードと遊びます"
EN: "Region free launcher" - "Select this to play a game from another region"
FR: "Lanceur de jeu dézoné" - "Sélectionnez cette option pour jouer à un jeu provenant d'une autre région"
DE: "Region free launcher" - "Wähle dies, um ein Spiel aus einer anderen Region zu spielen"
IT: "Launcher senza restrizioni regionali" - "Selezionare per giocare un gioco fuori regione"
ES: "Lanzador de región libre" - "Jugar con una tarjeta de juego de cualquier región"
ZH: "地区免费游戏启动" - "选择此选项可从另一区域玩游戏"
KO: "지역 제한 없는 게임 실행기" - "이 버튼을 선택하여 다른 지역 모드로 플레이 하세요"
NL: "Regio vrije launcher" - "Selecteer deze optie om het spel in een andere regio te spelen"
PT: "Lançador de região livre" - "Use para jogar jogos de qualquer região"
RU: "Играть независимо региона" - "Выберите, чтобы играть независимо региона"
TW: "地區免費遊戲啟動" - "選擇此選項可從另一區域玩遊戲"

**Comment by aschereT** [comment]
ID: "Launcher bebas daerah" - "Pilih ini untuk melancurkan game dari daerah lain"

**Pull request closed without merging**
